### PR TITLE
Changing formatting of plot titles in darwinscript

### PR DESCRIPTION
**Pull request by wholden**
Hi Matt, love the new web interface, very useful for machines without python installed. 

I was playing with the darwin width calculator and downloaded the generated python script. Thought it might be useful to tweak the script so that the plot titles are based on the variables defined in the script (xtal, h,k,l, polarization, energy) instead of hard-coded.

PS, I'm curious, is the live demo (https://millenia.cars.aps.anl.gov/xraydb/) deployed with the flask server? It runs very well. 

In the new generated script:
```python
plt.title(f'{xtal} {(h, k, l)}, "{polarization}" polar, E={energy} eV')
```

In the old generated script:
```python
plt.title('Ge (6 2 0), "s" polar, E=6400 eV')
```

### CODE REVIEW

**Comment by newville** [comment]
@wholden thanks, that's a good idea to push the formatting into the generated script.  I'll merge and deploy soon.

FWIW, the live version at  https://millenia.cars.aps.anl.gov/xraydb/ is running with apache and wsgi.   I can send the apache config paragraph if you'd like - it is a pretty basic wsgi config, that I use for a few python-web apps.

The live version at https://xraydb.xrayabsorption.org/ is also running with wsgi (and so must be using apache) but uses a hosting service and a web-based cPanel interface to config/enable web apps.

The Darwin width calculations and reported "width" values involved a few conversations with other folks - I *think* the reported values are the "accepted values".

**Comment by wholden** [comment]
@newville Thanks, that'd be great, please send the apache config paragraph. I don't have much experience with python webapps. I've played around with flask a bit, but was curious what solution you used, I'll check out apache+wsgi.

I appreciated your comment about the Darwin widths, I can imagine there are various opinions on that. I like the Darwin width feature. I did a quick comparison and the reported values seem to be slightly (but consistently) higher than the values reported on analyzer atlas (https://www.aps.anl.gov/Analyzer-Atlas/Analyzer-Atlas). For example, Cu Ka on Si 553 gives 13.2 microrad (xraydb) vs. 10.8 (analyzer atlas), but they could be averaging over polarizations (doesn't seem specified).

I did a quick comparison with the results from XRayTracer (https://github.com/kklmn/xrt), and they're consistent with xraydb. XRayTracer also does p polarization (which is narrower) which could explain the analyzer atlas discrepancy. I saw that p-polarization is not supported yet in xraydb. XRayTracer could perhaps be a point of reference if that was to be implemented.

image

Jupyter notebook attached in case any future readers are curious of the comparison.
[CompareIntegratedReflectivities_xraydb_xrt_notebook.zip](https://github.com/xraypy/xrayweb/files/5435567/CompareIntegratedReflectivities_xraydb_xrt_notebook.zip)

**Comment by newville** [comment]
@wholden Thanks! a few comments: 

a) the calc for analyzer crystals was using 's' polarization.  I believe that for analyzers it should be using 'unpolarized' (average 's' and 'p').  

b) there was a mistake for 'p' polarization and theta > 45 degrees (should use `abs(cos(2*theta))`!) that was breaking some of the calculations for `p` polarization.

I had not seen the Analyzer Atlas - that looks nice.  Yeah, I'll bet those calcs are correctly using unpolarized light which could explain the discrepancy - a few percent difference could also come from differences in anomalous scattering terms but probably only for Ge or heavy elements, no so much Si, especially if the absorption feature is mostly right.
I think I was aware the xrt could probably do these calcs, but did not know how to use it and I have not actually looked at that code.  So thanks for the notebook showing how to use it!

FWIW, the main "conversation" I was having earlier was about reporting "Darwin width" as "FWHM" of that peak or "width where reflectivity=1 in the absence of absorption".   It turns out that "FWHM" is an odd concept here, and that the latter completely non-physical value is what most people report for "Darwin width".   Well, except that  *some* people also just report sqrt(2) times that as what you will see in a "rocking curve scan", but which is, well sqrt(2) too big.   That's also why we show the 2-bounce curves: a second crystal does not increase the width, it decreases it slightly.    

Anyway, I think I have all these problems with polarization fixed and will push out fixes for XrayDB and the web apps soon (maybe later today or tomorrow).

**Comment by wholden** [comment]
@newville Yea I had noticed the Darwin width definition in the documentation (width where refl=1 without absorption) and it's certainly a bit convoluted (especially if you haven't read that section of AN&M), but if that's the standard then that's the standard. That's interesting about the 2-bounce curves, I hadn't noticed it actually decreases the width.

(a) Ah yes that makes sense. I saw your commit to xraydb including a new 'u' option for unpolarized. Quick work! Though given the non-physical definition for Darwin width, it kind of begs the question of what actual quantity would be represented by averaging the Darwin widths for the s & p polarizations. But at any rate the reflectivity vs angle/energy plots of unpolarized xrays are unambiguous.

(b) Gotcha, I saw p was an option but when it broke on the webpage, thought perhaps it hadn't been implemented. (And the docstring didn't say much about 'p', which I see is already also fixed!)

Sure thing, yea I've had some luck with XRT but the documentation is a little hard to navigate IMO. The code in my notebook is from their "using xrt as a calculator" page which has some other useful examples (https://xrt.readthedocs.io/calculator.html).

Thanks for the back and forth and quick fixes for everything. I hope I didn't end up making too much extra work for you. Great work on the new tools and web interface. If you find anything that might be easy to delegate, feel free to drop me a mention and maybe I can help out.

**Pull request merged**
