### PR TITLE
Starting to add xraydb.transmission_sample

### PR DESCRIPTION
**Pull request by easyXAFS**
@newville I was starting to play with integrating xraydb.transmission_sample into xrayweb. Nothing is actually ready to be pulled yet, so not sure if a PR was the proper channel to go through, but wanted to get something posted to avoid duplicate work.

It's been a while since I used flask/jinja, but I think I can probably sort through it (and it might be a good review) and get it integrated without deviating from the existing code style too much.

### CODE REVIEW

**Comment by newville** [comment]
@easyXAFS Thanks -- yeah that looks like the right basic approach!

**Comment by easyXAFS** [comment]
@newville Great thanks! I'll keep chipping away at this until there's something usefully deployable.

**Comment by easyXAFS** [comment]
@newville Okay I think I've got it in a usable format. Room for cleanup of course, but seems functional. Let me know what you think.

image

**Comment by newville** [comment]
@easyXAFS I like it!  This will be very useful,  I'd be happy to merge this as is.  

I think my only suggestions would be 

a) more explicitly write labels out like "Energy (eV)", "area (cm^2)", "Total Mass (mg)", etc
b) maybe do some formatting of the mass and absorption fractions and mass components.
b) maybe make a link to a script that can reproduce the calculations.

But also: I'd be happy to just merge and maybe make some of those cosmetic changes.

**Comment by easyXAFS** [comment]
@newville All great suggestions, I'll plan on doing all of them. For now the html table result was the minimum effort required to have readable output. It is just the output of a pandas `df.to_html()` method.

The suggestions might take some more time, so feel free to merge and close this PR and I can open another when needed, or we can leave this open.

**Comment by newville** [comment]
@easyXAFS  I agree -- I'll merge as is and get it up on the running web pages, and we can make cosmetic fixes sooner, later, no time pressure.   Maybe someone else will have a good comment or suggestion.  Again: thanks very much!!

**Comment by newville** [comment]
@easyXAFS I ended up making a couple of layout changes, mostly to avoid needing pandas.  But it's now live at
https://xraydb.xrayabsorption.org/transmission_sample/  !

**Comment by easyXAFS** [comment]
@newville Great work! Yea that layout looks way better. Thanks for getting it put together and deployed so quickly!

That pretty much covers most of the cosmetic work needed (though always room for improvement.).

That just leaves making the python script page. I've also considered adding a plot that shows the total absorption vs energy. It really gives a sense for how the sample behaves and a bit of how somewhat counterintuitive it is that the best sample is for total_mu=2.6 at the post-edge, regardless of concentration, thickness (though it changes obviously with how I-Z and I-T are measured of course).

I'm glad this worked out well. It was pretty easy to put together with the awesome back-end tools in xraydb. It'll be way more convenient to have this online. XAFSmass is a nice program, but a little tricky to install and launch. Web-page is much more accessible (especially for the less Python-friendly).

**Pull request merged**
